'use client';
import ImportWorker from '../lib/import.worker?worker';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowDownLeft,ArrowUpRight,Check,ChevronLeft,ChevronRight,Database,Download,FileSpreadsheet,LayoutDashboard,LoaderCircle,LockKeyhole,Plus,Search,Settings2,ShieldCheck,Sparkles,Upload,Workflow,X} from 'lucide-react';
import {Sidebar,SidebarProvider,SidebarHeader,SidebarContent,SidebarFooter,SidebarTrigger} from '@/components/ui/sidebar';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AreaChart,Area,ResponsiveContainer,XAxis,YAxis,CartesianGrid,Tooltip,PieChart,Pie,Cell as ChartCell,BarChart,Bar} from 'recharts';
import {analyze,dateValue,demoBook,detectHeader,empty,filterRows,inferMapping,normalize,numberValue,prepare,toCSV,type Book,type Cell,type Filters,type Mapping,type Rules} from '@/lib/engine';

const COLORS=['#1aab80','#91d4bc','#9e8ae8','#f0bb7a','#709bcd','#d1d8e1','#a9b5bb'];
const defaults:Rules={trim:true,deduplicate:false};
const cleanFilters:Filters={search:'',category:'all',start:'',end:''};
const fmt=(n:number,currency=false)=>new Intl.NumberFormat('pt-BR',{style:currency?'currency':'decimal',currency:'BRL',maximumFractionDigits:currency?2:2}).format(n);
const compact=(n:number)=>new Intl.NumberFormat('pt-BR',{notation:'compact',maximumFractionDigits:1}).format(n);
const month=(s:string)=>/^\d{4}-\d{2}$/.test(s)?new Intl.DateTimeFormat('pt-BR',{month:'short',year:'2-digit',timeZone:'UTC'}).format(new Date(s+'-01T00:00:00Z')):s;
function Pick({label,value,options,onChange}:{label:string;value:string;options:{value:string;label:string}[];onChange:(v:string)=>void}){
 return <label className="pick"><span>{label}</span><Select value={value} onValueChange={v=>v!==null&&onChange(String(v))} items={options}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></label>
}
function download(content:string,name:string,mime:string){const url=URL.createObjectURL(new Blob([content],{type:mime}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function Home(){
 const [book,setBook]=useState<Book>(()=>demoBook());const [sheet,setSheet]=useState(0);const [header,setHeader]=useState(0);
 const [rules,setRules]=useState<Rules>(defaults);const [rulesReady,setRulesReady]=useState(false);
 const [mapping,setMapping]=useState<Mapping|null>(null);const [tab,setTab]=useState('overview');const [filters,setFilters]=useState<Filters>(cleanFilters);
 const [configure,setConfigure]=useState(false);const [help,setHelp]=useState(false);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [error,setError]=useState('');
 const [drag,setDrag]=useState(false);const [page,setPage]=useState(0);const [sort,setSort]=useState<{column:number;desc:boolean}>({column:-1,desc:false});
 const input=useRef<HTMLInputElement>(null);const workerRef=useRef<Worker|null>(null);const timeoutRef=useRef<ReturnType<typeof setTimeout>|null>(null);
 const data=useMemo(()=>prepare(book.sheets[sheet]?.data||[],header,rules),[book,sheet,header,rules]);
 const map=useMemo(()=>mapping??inferMapping(data),[mapping,data]);
 const rows=useMemo(()=>filterRows(data,map,filters),[data,map,filters]);const result=useMemo(()=>analyze(rows,map),[rows,map]);
 const categories=useMemo(()=>[...new Set(data.rows.map(r=>String(r[map.group]??'Sem categoria')))].sort((a,b)=>a.localeCompare(b,'pt-BR')),[data,map.group]);
 const finance=map.mode==='finance';const currency=map.currency;
 const metricName=data.columns[map.metric]?.name??'Registros';const groupName=data.columns[map.group]?.name??'Categoria';
 const money=(n:number)=>fmt(n,currency);
 const sorted=useMemo(()=>{if(sort.column<0)return rows;const col=data.columns[sort.column];return [...rows].sort((a,b)=>{const av=a[sort.column],bv=b[sort.column];let diff=0;if(col?.kind==='number')diff=(numberValue(av)??-Infinity)-(numberValue(bv)??-Infinity);else if(col?.kind==='date')diff=(dateValue(av)??'').localeCompare(dateValue(bv)??'');else diff=String(av??'').localeCompare(String(bv??''),'pt-BR',{numeric:true});return sort.desc?-diff:diff})},[rows,sort,data.columns]);
 const pages=Math.max(1,Math.ceil(sorted.length/12));const safePage=Math.min(page,pages-1);
 const completeness=data.rows.length&&data.columns.length?100*(1-data.missing/(data.rows.length*data.columns.length)):0;
 const distribution=result.groups.filter(g=>g.value!==0);
 const pieData=distribution.slice(0,6);if(distribution.length>6)pieData.push({name:'Demais categorias',value:distribution.slice(6).reduce((s,g)=>s+g.value,0),count:0});
 const chartData=map.date>=0?result.timeline:result.groups.slice(0,12);
 const numOptions=[{value:'-1',label:'Contar registros'},...data.columns.filter(c=>c.kind!=='date').map(c=>({value:String(c.index),label:c.name}))];
 const allOptions=[{value:'-1',label:'Nenhuma'},...data.columns.map(c=>({value:String(c.index),label:c.name}))];
 const activeFilters=filters.search||filters.category!=='all'||filters.start||filters.end;
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('nexo-rules')||'null');if(saved&&typeof saved.trim==='boolean'&&typeof saved.deduplicate==='boolean')setRules(saved)}catch{}setRulesReady(true);return()=>{workerRef.current?.terminate();if(timeoutRef.current)clearTimeout(timeoutRef.current)}},[]);
 useEffect(()=>{if(rulesReady)try{localStorage.setItem('nexo-rules',JSON.stringify(rules))}catch{}},[rules,rulesReady]);
 useEffect(()=>{setPage(0)},[filters,book,sheet,header,rules,map.metric,map.group]);
 const toolSnapshot=useRef({result,map,metricName,rows:rows.length});toolSnapshot.current={result,map,metricName,rows:rows.length};
 useEffect(()=>{
 type Tool={name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown};
 const context=(document as Document&{modelContext?:{registerTool:(tool:Tool,opts:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
 if(!context?.registerTool)return;const lifecycle=new AbortController();
 try{Promise.resolve(context.registerTool({name:'read_dashboard_summary',description:'Lê os indicadores calculados da visão filtrada atual do Nexo. Os nomes vêm da planilha do usuário.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Esperado um objeto vazio.');const s=toolSnapshot.current;return {mode:s.map.mode,metric:s.metricName,rows:s.rows,total:s.result.total,income:s.result.income,expense:s.result.expense,invalid:s.result.invalid}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort();
 },[]);
 function updateMap(patch:Partial<Mapping>){setMapping({...map,...patch});if('group'in patch)setFilters(f=>({...f,category:'all'}));if('date'in patch)setFilters(f=>({...f,start:'',end:''}))}
 function selectSheet(index:number){setSheet(index);setHeader(detectHeader(book.sheets[index].data));setMapping(null);setFilters(cleanFilters);setSort({column:-1,desc:false})}
 function loadDemo(kind:string){if(busy)return;setBook(demoBook(kind));setSheet(0);setHeader(0);setMapping(null);setFilters(cleanFilters);setSort({column:-1,desc:false});setTab('overview');setError('');setNotice('Exemplo carregado. Os dados são fictícios.')}
 async function importFile(file?:File){
 if(!file)return;if(busy)return;
 if(!/\.(csv|tsv|xlsx|xls)$/i.test(file.name)){setError('Escolha um arquivo CSV, TSV, XLSX ou XLS.');return}
 if(file.size>15*1024*1024){setError('O limite é de 15 MB por arquivo. Divida a planilha e tente novamente.');return}
 setBusy(true);setError('');setNotice('Lendo '+file.name+'…');
 let worker:Worker|null=null;
 const finish=()=>{worker?.terminate();if(timeoutRef.current)clearTimeout(timeoutRef.current);timeoutRef.current=null;workerRef.current=null;setBusy(false)};
 try{
 worker=new ImportWorker();workerRef.current=worker;
 timeoutRef.current=setTimeout(()=>{finish();setError('A leitura ultrapassou 30 segundos. Tente um arquivo menor.');setNotice('')},30000);
 worker.onmessage=(event:MessageEvent<{book?:Book;error?:string}>)=>{
 finish();if(event.data.error){setError(event.data.error);setNotice('');return}const next=event.data.book;if(!next)return;
 const nextHeader=detectHeader(next.sheets[0].data);const nextData=prepare(next.sheets[0].data,nextHeader,rules);
 const same=data.columns.length===nextData.columns.length&&data.columns.every((c,i)=>c.name===nextData.columns[i].name);
 setBook(next);setSheet(0);setHeader(nextHeader);setMapping(same?map:null);setFilters(cleanFilters);setSort({column:-1,desc:false});setTab('overview');setNotice('Importação concluída. '+fmt(nextData.rows.length)+' registros analisados'+(same?' com a configuração anterior.':'.'));};
 worker.onerror=()=>{finish();setNotice('');setError('Não foi possível processar o arquivo. Confira se ele está íntegro e sem senha.')};
 const buffer=await file.arrayBuffer();worker.postMessage({buffer,name:file.name},[buffer]);
 }catch(cause){console.error('Falha no importador',cause);finish();setNotice('');setError('Não foi possível abrir o arquivo. Tente novamente.')}
 }
 function exportCSV(){download(toCSV(data.columns,sorted),'nexo-dados-filtrados.csv','text/csv;charset=utf-8');setNotice('CSV exportado com os filtros e a ordenação atuais.')}
 function exportReport(){download(JSON.stringify({source:book.name,sheet:book.sheets[sheet].name,demo:!!book.demo,generatedAt:new Date().toISOString(),filters,mapping:{...map,metricName,groupName},rules,summary:result,quality:{missing:data.missing,duplicates:data.duplicates,removed:data.removed,completeness}},null,2),'nexo-relatorio.json','application/json');setNotice('Relatório da análise exportado.')}
 const kpis=finance?[{label:'Receitas',value:money(result.income),note:'Entradas classificadas',icon:ArrowUpRight,style:'mint'},{label:'Despesas',value:money(result.expense),note:'Saídas classificadas',icon:ArrowDownLeft,style:'orange'},{label:'Saldo do período',value:money(result.balance),note:'Receitas menos despesas',icon:Activity,style:'purple'},{label:'Registros analisados',value:fmt(rows.length),note:result.invalid?result.invalid+' valores inválidos':'Na seleção atual',icon:Database,style:'blue'}]:[{label:map.metric<0?'Registros':'Total · '+metricName,value:map.metric<0?fmt(rows.length):money(result.total),note:'Na seleção atual',icon:Activity,style:'mint'},{label:map.metric<0?'Colunas':'Média por registro',value:map.metric<0?fmt(data.columns.length):money(result.average),note:map.metric<0?'Detectadas na planilha':fmt(result.valid)+' valores numéricos válidos',icon:ArrowUpRight,style:'purple'},{label:'Categorias',value:fmt(result.groups.length),note:map.group>=0?groupName:'Sem agrupamento',icon:Database,style:'orange'},{label:'Registros analisados',value:fmt(rows.length),note:result.invalid?result.invalid+' valores inválidos':'Na seleção atual',icon:FileSpreadsheet,style:'blue'}];
 return <SidebarProvider style={{'--sidebar-width':'238px'} as React.CSSProperties}>
 <Sidebar><SidebarHeader><a href="/" className="brand" aria-label="Nexo, página inicial"><span><Workflow size={23}/></span>nexo<b>.</b></a><div className="workspace"><span className="avatar">A</span><div>Meu painel<small>Sessão local</small></div><ChevronRight size={15}/></div></SidebarHeader><SidebarContent><p className="nav-label">SEU PAINEL</p>{[{id:'overview',name:'Visão geral',icon:LayoutDashboard},{id:'data',name:'Explorar dados',icon:Database},{id:'rules',name:'Automações',icon:Workflow},{id:'quality',name:'Qualidade dos dados',icon:ShieldCheck}].map(n=><button key={n.id} className={'nav-item '+(tab===n.id?'active':'')} onClick={()=>setTab(n.id)}><n.icon size={18}/>{n.name}</button>)}<p className="nav-label">EXPERIMENTE COM EXEMPLOS</p>{[{id:'finance',name:'Finanças'},{id:'sales',name:'Vendas'},{id:'stock',name:'Estoque'}].map((s,i)=><button className={'nav-item '+(book.demo===s.id?'demo-selected':'')} key={s.id} onClick={()=>loadDemo(s.id)} disabled={busy}><i style={{background:COLORS[i*2]}}/>{s.name}<small>demo</small></button>)}</SidebarContent><SidebarFooter><div className="private-note"><LockKeyhole size={18}/><strong>Seus dados ficam com você</strong><p>As planilhas são processadas no seu navegador e não são salvas ao fechar a página.</p></div><div className="sidebar-bottom"><span className="avatar">A</span><div>Arthur<small>Sessão local</small></div><button className="icon-button" aria-label="Ajuda" onClick={()=>setHelp(true)}>?</button></div></SidebarFooter></Sidebar>
 <main className="main"><header className="topbar"><div className="breadcrumb"><SidebarTrigger/><span>Meu painel</span><ChevronRight size={14}/><strong>{tab==='rules'?'Automações':tab==='quality'?'Qualidade':tab==='data'?'Explorar dados':'Visão geral'}</strong></div><span className="local-badge"><i/>Processamento local</span></header><div className="page">
 <div className="page-heading"><div><div className="eyebrow">SEUS DADOS, MAIS CLAROS</div><h1>{tab==='rules'?'Automações':tab==='quality'?'Qualidade dos dados':tab==='data'?'Explore cada detalhe.':'Visão geral'}</h1><p>{tab==='rules'?'Uma rotina mais simples, a cada importação.':'Da planilha à próxima decisão.'}</p></div><div className="heading-actions"><button className="secondary-button" onClick={exportReport}><Download size={16}/>Relatório</button><button className="primary-button" disabled={busy} onClick={()=>input.current?.click()}>{busy?<LoaderCircle className="spin" size={18}/>:<Plus size={18}/>} {busy?'Importando…':'Importar planilha'}</button></div><input hidden ref={input} type="file" accept=".csv,.xlsx,.xls,.tsv" onChange={e=>{void importFile(e.target.files?.[0]);e.target.value=''}}/></div>
 {(error||notice)&&<div className={'notice '+(error?'error':'')} role={error?'alert':'status'}>{busy?<LoaderCircle className="spin" size={16}/>:error?<Activity size={16}/>:<Check size={16}/>}<span>{error||notice}</span>{!busy&&<button aria-label="Fechar aviso" onClick={()=>{setError('');setNotice('')}}><X size={15}/></button>}</div>}
 <div className="source-bar"><span className="source-icon"><FileSpreadsheet size={22}/></span><div className="source-text"><strong title={book.name}>{book.name}</strong><p>{book.demo?'Dados de demonstração':'Arquivo importado'} · {fmt(data.rows.length)} registros · {data.columns.length} colunas</p></div>{book.sheets.length>1&&<Pick label="Aba" value={String(sheet)} onChange={v=>selectSheet(+v)} options={book.sheets.map((s,i)=>({value:String(i),label:s.name}))}/>}<span className="status-badge"><Sparkles size={14}/>Análise automática</span><button className={'icon-button '+(configure?'is-active':'')} onClick={()=>setConfigure(!configure)} aria-label="Configurar análise" aria-expanded={configure}><Settings2 size={18}/></button></div>
 {configure&&<section className="config-panel"><div className="section-title"><h2>Configure a leitura da planilha</h2><span>Ajuste as colunas usadas nos indicadores.</span></div><div className="config-grid"><Pick label="Linha do cabeçalho" value={String(header)} onChange={v=>{setHeader(+v);setMapping(null);setFilters(cleanFilters);setSort({column:-1,desc:false})}} options={book.sheets[sheet].data.slice(0,Math.min(30,book.sheets[sheet].data.length)).map((_,i)=>({value:String(i),label:'Linha '+(i+1)}))}/><Pick label="Tipo de análise" value={map.mode} onChange={v=>updateMap({mode:v as Mapping['mode']})} options={[{value:'general',label:'Geral'},{value:'finance',label:'Financeira'}]}/><Pick label="Indicador numérico" value={String(map.metric)} onChange={v=>updateMap({metric:+v})} options={numOptions}/><Pick label="Agrupar por" value={String(map.group)} onChange={v=>updateMap({group:+v})} options={allOptions}/><Pick label="Coluna de data" value={String(map.date)} onChange={v=>updateMap({date:+v})} options={allOptions}/>{finance&&<Pick label="Tipo de movimentação" value={String(map.type)} onChange={v=>updateMap({type:+v})} options={[{value:'-1',label:'Usar sinal do valor'},...allOptions.slice(1)]}/>}<label className="switch-line"><Switch checked={currency} onCheckedChange={v=>updateMap({currency:v})} aria-label="Exibir valores em reais"/>Exibir valores em reais</label></div><p className="config-note">Datas: dia/mês/ano ou ano-mês-dia. Valores de texto: 1.234,56 (BR) e 1,234.56 (EUA). Em caso ambíguo, “1.234” significa mil duzentos e trinta e quatro.{finance?' No modo financeiro, a coluna de tipo prevalece sobre o sinal; sem ela, positivos são entradas e negativos são saídas.':''}</p></section>}
 <div className="view-toolbar"><Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList variant="line"><TabsTrigger value="overview">Visão geral</TabsTrigger><TabsTrigger value="data">Dados da planilha</TabsTrigger><TabsTrigger value="quality">Qualidade</TabsTrigger><TabsTrigger value="rules">Automações</TabsTrigger></TabsList></Tabs><span className="subtle">{book.demo?'Modo demonstração':'Dados da sessão'}</span></div>
 {tab!=='rules'&&<div className="filters"><label className="search-box"><Search size={16}/><input aria-label="Buscar na planilha" placeholder="Buscar nos dados..." value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/></label>{map.group>=0&&<Pick label={groupName} value={filters.category} onChange={v=>setFilters({...filters,category:v})} options={[{value:'all',label:'Todas as categorias'},...categories.map(c=>({value:c,label:c}))]}/>} {map.date>=0&&<div className="date-filters"><label>De<input aria-label="Data inicial" type="date" value={filters.start} max={filters.end||undefined} onChange={e=>setFilters({...filters,start:e.target.value})}/></label><label>Até<input aria-label="Data final" type="date" value={filters.end} min={filters.start||undefined} onChange={e=>setFilters({...filters,end:e.target.value})}/></label></div>}{activeFilters&&<button className="text-button" onClick={()=>setFilters(cleanFilters)}>Limpar filtros</button>}</div>}
 {tab==='overview'&&<><section className="kpi-grid">{kpis.map(k=><article className="kpi" key={k.label}><div className="kpi-title">{k.label}<span className={'kpi-icon '+k.style}><k.icon size={17}/></span></div><strong title={k.value}>{k.value}</strong><small>{k.note}</small></article>)}</section>
 {rows.length===0?<div className="empty-state"><Database size={32}/><h2>Nenhum registro nesta seleção</h2><p>Altere os filtros ou confira a linha do cabeçalho.</p><button className="secondary-button" onClick={()=>setFilters(cleanFilters)}>Limpar filtros</button></div>:<section className="chart-grid"><article className="panel"><div className="panel-heading"><div><h2>{finance?'Movimentação financeira':map.date>=0?'Evolução de '+metricName:metricName+' por '+groupName}</h2><p>{map.date>=0?'Acompanhe a evolução dos seus resultados':'Comparação entre as primeiras 12 categorias'}</p></div><span className="chart-chip">{map.date>=0?'Mensal':'Por categoria'}</span></div><div className="chart-legend"><span><i/>{finance?'Receitas':metricName}</span>{finance&&<span><i className="purple-dot"/>Despesas</span>}</div><div className="line-chart">{chartData.length?<ResponsiveContainer width="100%" height="100%">{map.date>=0?<AreaChart data={chartData} margin={{top:12,right:12,bottom:0,left:0}}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#18ad7f" stopOpacity={.2}/><stop offset="100%" stopColor="#18ad7f" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf0f3" strokeDasharray="4 5"/><XAxis dataKey="name" tickFormatter={month} axisLine={false} tickLine={false} tick={{fill:'#88919e',fontSize:12}} dy={10}/><YAxis axisLine={false} tickLine={false} tickFormatter={compact} tick={{fill:'#88919e',fontSize:12}} width={55}/><Tooltip formatter={v=>money(Number(v))} labelFormatter={v=>month(String(v))}/><Area name={finance?'Receitas':metricName} type="monotone" dataKey={finance?'income':'value'} stroke="#19a97f" strokeWidth={2.5} fill="url(#fill)" dot={chartData.length===1}/>{finance&&<Area name="Despesas" type="monotone" dataKey="expense" stroke="#9a8ae7" strokeWidth={2} fill="transparent" dot={chartData.length===1}/>}</AreaChart>:<BarChart data={chartData}><CartesianGrid vertical={false} stroke="#edf0f3"/><XAxis dataKey="name" tick={{fontSize:12}} tickFormatter={v=>String(v).slice(0,12)} axisLine={false} tickLine={false}/><YAxis tickFormatter={compact} tick={{fontSize:12}} axisLine={false} tickLine={false}/><Tooltip formatter={v=>money(Number(v))}/><Bar name={finance?'Despesas':metricName} dataKey="value" fill="#1aab80" radius={[5,5,0,0]}/></BarChart>}</ResponsiveContainer>:<div className="empty-state">Nenhuma data válida para construir a evolução.</div>}</div>{result.undated>0&&<p className="chart-footnote">{result.undated} registros sem data válida não aparecem na evolução.</p>}</article>
 <article className="panel"><div className="panel-heading"><div><h2>{finance?'Despesas por categoria':'Distribuição por '+groupName}</h2><p>{finance?'Como os recursos se distribuem':metricName+' na seleção atual'}</p></div></div>{pieData.length?finance?<><div className="real-donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={pieData} dataKey="value" nameKey="name" innerRadius={62} outerRadius={80} paddingAngle={3} startAngle={90} endAngle={-270}>{pieData.map((g,i)=><ChartCell key={g.name} fill={COLORS[i]}/>)}</Pie><Tooltip formatter={v=>money(Number(v))}/></PieChart></ResponsiveContainer><div className="donut-center"><small>Total de despesas</small><strong>{compact(result.expense)}</strong></div></div><div className="category-legend">{pieData.map((g,i)=><div key={g.name}><span title={g.name}><i style={{background:COLORS[i]}}/>{g.name}</span><strong>{fmt(result.expense?g.value/result.expense*100:0)}%</strong></div>)}</div></>:<div className="rank-list">{pieData.map((g,i)=><div key={g.name}><div><span><i style={{background:COLORS[i]}}/>{g.name}</span><strong>{money(g.value)}</strong></div><div className="rank-track"><span style={{width:Math.max(2,Math.abs(g.value)/Math.max(...pieData.map(g=>Math.abs(g.value)),1)*100)+'%',background:COLORS[i]}}/></div></div>)}</div>:<div className="empty-state"><p>Sem valores para esta distribuição.</p></div>}</article></section>}
 <div className="insight"><Sparkles size={23}/><div><strong>{result.invalid||result.unclassified?'Alguns registros precisam de atenção':finance?result.balance>=0?'As entradas superam as saídas nesta seleção.':'As saídas superam as entradas nesta seleção.':'Seu indicador mais claro, em um só lugar.'}</strong><p>{result.invalid||result.unclassified?result.invalid+' valores não numéricos e '+result.unclassified+' tipos não reconhecidos. Revise a configuração da análise.':finance?'Saldo de '+money(result.balance)+'. '+fmt(rows.length)+' registros considerados, incluindo todos os status.':fmt(result.valid)+' valores válidos em “'+metricName+'”. Altere a coluna ou o agrupamento em Configurar análise.'}</p></div><button className="icon-button" aria-label="Ajustar análise" onClick={()=>setConfigure(true)}><ArrowUpRight size={22}/></button></div>
 </>}
 {tab==='data'&&<article className="panel data-panel"><div className="panel-heading"><div><h2>Dados da planilha</h2><p>{fmt(rows.length)} de {fmt(data.rows.length)} registros · Clique no cabeçalho para ordenar</p></div><button className="secondary-button" onClick={exportCSV} disabled={!rows.length}><Download size={16}/>Exportar CSV</button></div><Table><TableHeader><TableRow>{data.columns.map(c=><TableHead key={c.index} aria-sort={sort.column===c.index?sort.desc?'descending':'ascending':'none'}><button onClick={()=>setSort({column:c.index,desc:sort.column===c.index?!sort.desc:false})}>{c.name}<small>{c.kind==='number'?'123':c.kind==='date'?'Data':'Texto'} {sort.column===c.index?sort.desc?'↓':'↑':''}</small></button></TableHead>)}</TableRow></TableHeader><TableBody>{sorted.slice(safePage*12,(safePage+1)*12).map((r,i)=><TableRow key={safePage*12+i}>{data.columns.map(c=><TableCell key={c.index} title={String(r[c.index]??'')}>{empty(r[c.index])?<span className="muted-cell">—</span>:c.kind==='number'&&numberValue(r[c.index])!==null?fmt(numberValue(r[c.index])!):String(r[c.index])}</TableCell>)}</TableRow>)}</TableBody></Table>{!rows.length&&<div className="empty-state">Nenhum registro corresponde aos filtros.</div>}<div className="pagination"><span>{rows.length?safePage*12+1:0}–{Math.min((safePage+1)*12,rows.length)} de {fmt(rows.length)}</span><div><button className="icon-button" disabled={safePage===0} onClick={()=>setPage(safePage-1)} aria-label="Página anterior"><ChevronLeft size={17}/></button><span>Página {safePage+1} de {pages}</span><button className="icon-button" disabled={safePage>=pages-1} onClick={()=>setPage(safePage+1)} aria-label="Próxima página"><ChevronRight size={17}/></button></div></div></article>}
 {tab==='quality'&&<><div className="quality-summary"><ShieldCheck size={32}/><div><h2>{fmt(completeness)}% das células preenchidas</h2><p>Qualidade da aba inteira, após aplicar as regras de limpeza. Os filtros afetam apenas a análise numérica abaixo.</p></div></div><div className="quality-grid">{[{label:'Células vazias',value:data.missing,note:'Valores ausentes nas linhas mantidas'},{label:'Linhas repetidas',value:data.duplicates,note:rules.deduplicate?data.removed+' removidas pela automação':'Mantidas até você ativar a remoção'},{label:'Linhas vazias',value:data.emptyRows,note:'Ignoradas automaticamente'},{label:'Valores inválidos',value:result.invalid,note:'Na coluna numérica e filtros atuais'}].map(q=><article className="kpi" key={q.label}><div className="kpi-title">{q.label}</div><strong>{fmt(q.value)}</strong><small>{q.note}</small></article>)}</div><article className="panel"><h2>Estrutura detectada</h2><Table><TableHeader><TableRow><TableHead>Coluna</TableHead><TableHead>Tipo detectado</TableHead><TableHead>Células vazias</TableHead><TableHead>Preenchimento</TableHead></TableRow></TableHeader><TableBody>{data.columns.map(c=><TableRow key={c.index}><TableCell>{c.name}</TableCell><TableCell>{c.kind==='number'?'Número':c.kind==='date'?'Data':'Texto'}</TableCell><TableCell>{c.missing}</TableCell><TableCell>{fmt(data.rows.length?(1-c.missing/data.rows.length)*100:0)}%</TableCell></TableRow>)}</TableBody></Table></article></>}
 {tab==='rules'&&<><div className="automation-intro"><span className="source-icon"><Workflow size={24}/></span><div><h2>Configure uma vez. Aplique a cada arquivo.</h2><p>As regras são aplicadas à planilha atual e às próximas importações neste navegador.</p></div><span className="status-badge"><i/>{1+Number(rules.trim)+Number(rules.deduplicate)} regras ativas</span></div><article className="panel rules-panel"><div className="rule-row"><div className="rule-icon"><Database size={20}/></div><div><strong>Ignorar linhas completamente vazias</strong><p>Evita que espaços sem dados alterem a contagem de registros.</p></div><span className="fixed-rule"><Check size={15}/>Sempre ativa</span></div><div className="rule-row"><div className="rule-icon"><Sparkles size={20}/></div><div><strong>Remover espaços extras</strong><p>Limpa espaços no início e no fim dos textos para uniformizar categorias.</p></div><Switch checked={rules.trim} onCheckedChange={v=>setRules({...rules,trim:v})} aria-label="Remover espaços extras"/></div><div className="rule-row"><div className="rule-icon"><FileSpreadsheet size={20}/></div><div><strong>Remover linhas duplicadas</strong><p>Mantém a primeira ocorrência quando todas as células da linha são iguais.</p></div><Switch checked={rules.deduplicate} onCheckedChange={v=>setRules({...rules,deduplicate:v})} aria-label="Remover linhas duplicadas"/></div></article><div className="insight"><Sparkles size={23}/><div><strong>Indicadores recalculados automaticamente</strong><p>A cada importação, filtro ou mudança de regra, o Nexo atualiza os resultados. Ao reimportar os mesmos cabeçalhos, a configuração de análise é mantida durante esta sessão.</p></div></div><p className="config-note">O arquivo original permanece intacto. O Nexo não monitora alterações no Excel: importe novamente a planilha atualizada. Somente as preferências de limpeza ficam salvas neste navegador.</p></>}
 <button className={'dropzone '+(drag?'dragging':'')} disabled={busy} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(e.dataTransfer.files.length>1){setError('Importe um arquivo por vez.');return}void importFile(e.dataTransfer.files[0])}} onClick={()=>input.current?.click()}><span className="upload-icon">{busy?<LoaderCircle size={21} className="spin"/>:<Upload size={21}/>}</span><span><strong>{busy?'Preparando seus dados…':'Suas planilhas têm mais para contar.'}</strong><small>Arraste um arquivo ou <b>clique para importar</b> · XLSX, XLS, CSV ou TSV · Até 15 MB</small></span></button>
 <footer className="page-footer"><span>nexo. <span>Clareza em cada célula.</span></span><button onClick={()=>setHelp(true)}>Como funciona <ChevronRight size={13}/></button></footer></div></main>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent className="help-dialog"><DialogHeader><DialogTitle>Da planilha ao dashboard</DialogTitle><DialogDescription>Importe, confira e explore os seus dados.</DialogDescription></DialogHeader><ol><li><strong>Importe um arquivo.</strong> Excel com várias abas, CSV e TSV. Até 15 MB, 50.000 registros e 200 colunas por aba.</li><li><strong>Confira a leitura.</strong> Use o ícone de ajustes ao lado do arquivo para escolher o cabeçalho, o indicador, a categoria e a data.</li><li><strong>Explore e exporte.</strong> Filtre, ordene, aplique as regras de limpeza e baixe os dados em CSV ou a análise em JSON.</li></ol><p>O modo financeiro reconhece Receita/Despesa, Entrada/Saída e Crédito/Débito. Sem coluna de tipo, utiliza o sinal dos valores. Textos de tipo não reconhecidos ficam fora do saldo.</p><p>Fórmulas do Excel usam o último resultado salvo no arquivo; não são recalculadas. Macros não são executadas. Planilhas com títulos mesclados podem precisar de ajuste do cabeçalho. Limite adicional: 300.000 células por aba e 500.000 por arquivo.</p><p>Os exemplos são fictícios. Indicadores incluem todos os status; use a busca para restringir a seleção.</p></DialogContent></Dialog>
 </SidebarProvider>
}



